terminate called after throwing an instance of 'double'